
FIND_PATH ( LibWEBSOCKETS_INCLUDE_DIRS libwebsockets.h
  /usr/local/include
  /usr/include
  )

FIND_LIBRARY ( LibWEBSOCKETS_LIBRARIES websockets
  /usr/local/lib
  /usr/lib
  )

GET_FILENAME_COMPONENT( LibWEBSOCKETS_LIBRARY_DIR ${LibWEBSOCKETS_LIBRARIES} PATH )

SET ( LibWEBSOCKETS_FOUND "NO" )
IF ( LibWEBSOCKETS_INCLUDE_DIRS )
  IF ( LibWEBSOCKETS_LIBRARIES )
    SET ( LibWEBSOCKETS_FOUND "YES" )
  ENDIF ( LibWEBSOCKETS_LIBRARIES )
ENDIF ( LibWEBSOCKETS_INCLUDE_DIRS )

MARK_AS_ADVANCED(
  LibWEBSOCKETS_LIBRARY_DIR
  LibWEBSOCKETS_INCLUDE_DIRS
  LibWEBSOCKETS_LIBRARIES
  )